import { Language } from './types';

export const TRANSLATIONS = {
  zh: {
    title: 'Excel/CSV 字段提取与 JSON 生成器',
    darkMode: '暗色模式',
    lightMode: '亮色模式',
    uploadTitle: '上传文件',
    uploadDesc: '支持 .csv, .xls, .xlsx 格式',
    clickToUpload: '点击上传或拖拽文件',
    step1Title: '第一步：选择表头所在行',
    row1: '第一行',
    row2: '第二行',
    step2Title: '第二步：勾选需要提取的字段',
    selectAll: '全选',
    deselectAll: '取消全选',
    step3Title: '第三步：元数据配置',
    metadataDesc: '在此处编写 JSON 格式的元数据（将合并到根节点）：',
    metadataPlaceholder: '{\n  "version": "1.0",\n  "author": "User"\n}',
    updateMetadata: '确认/更新元数据',
    step4Title: '第四步：结构配置与预览',
    rootKeyConfig: '主数据列表的键名（表头）：',
    useCustomName: '自定义名称 (生成数组格式)',
    useFieldName: '使用选中的字段名 (生成对象字典格式)',
    enterRootName: '输入键名 (例如: items)',
    selectField: '选择作为 Key 的字段',
    reorderDesc: '拖拽或点击箭头调整字段在 JSON 对象中的顺序：',
    previewTitle: 'JSON 预览 (显示第一条数据)',
    exportBtn: '导出 JSON 文件',
    resetBtn: '重置',
    errorInvalidJson: '元数据 JSON 格式错误',
    errorNoFile: '请先上传文件',
    moveUp: '上移',
    moveDown: '下移',
    totalRecords: '共 {{count}} 条记录',
  },
  en: {
    title: 'Excel/CSV Field Extractor & JSON Generator',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    uploadTitle: 'Upload File',
    uploadDesc: 'Supports .csv, .xls, .xlsx',
    clickToUpload: 'Click to upload or drag & drop',
    step1Title: 'Step 1: Select Header Row',
    row1: 'Row 1',
    row2: 'Row 2',
    step2Title: 'Step 2: Select Fields',
    selectAll: 'Select All',
    deselectAll: 'Deselect All',
    step3Title: 'Step 3: Metadata Configuration',
    metadataDesc: 'Write metadata in JSON format (merged to root):',
    metadataPlaceholder: '{\n  "version": "1.0",\n  "author": "User"\n}',
    updateMetadata: 'Confirm/Update Metadata',
    step4Title: 'Step 4: Configuration & Preview',
    rootKeyConfig: 'Key for the main data list (Header):',
    useCustomName: 'Custom Name (Array Output)',
    useFieldName: 'Use selected field name (Dictionary Output)',
    enterRootName: 'Enter key name (e.g. items)',
    selectField: 'Select Key Field',
    reorderDesc: 'Reorder fields for the JSON object:',
    previewTitle: 'JSON Preview (First Record)',
    exportBtn: 'Export JSON',
    resetBtn: 'Reset',
    errorInvalidJson: 'Invalid Metadata JSON format',
    errorNoFile: 'Please upload a file first',
    moveUp: 'Move Up',
    moveDown: 'Move Down',
    totalRecords: 'Total {{count}} records',
  }
};

export const DEFAULT_METADATA = ``;